// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Minimal_Api.Data;

#nullable disable

namespace Minimal_Api.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20250106133317_InitMinimalApi")]
    partial class InitMinimalApi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Minimal_Api.Model.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7a09af2-dc8b-4fa4-93d1-c68df8c51753"),
                            Description = "Book 1 Description",
                            Name = "Book 1"
                        },
                        new
                        {
                            Id = new Guid("6c5c55d3-4f54-4b90-80d4-d43b9b524d8a"),
                            Description = "Book 2 Description",
                            Name = "Book 2"
                        },
                        new
                        {
                            Id = new Guid("e6d5b92f-3ac1-4c69-a717-5c0c75091649"),
                            Description = "Book 3 Description",
                            Name = "Book 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
